using Core.Application.Common;
using Core.Application.DTO.Recipe;
using Core.Application.Interfaces.Services;
using Core.Application.Options;
using Core.Domain.Enums;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Options;
using Microsoft.Extensions.Logging;
namespace Infrastructure.Services;
public sealed class LocalRecipeMediaStorage : IRecipeMediaStorage
{
 private const string PublicPrefix = "/images/recipes/";
 private static readonly IReadOnlyDictionary<string,(string ContentType,RecipeMediaType Type)> Extensions = new Dictionary<string,(string,RecipeMediaType)>(StringComparer.OrdinalIgnoreCase) { [".jpg"]=("image/jpeg",RecipeMediaType.Image),[".jpeg"]=("image/jpeg",RecipeMediaType.Image),[".png"]=("image/png",RecipeMediaType.Image),[".webp"]=("image/webp",RecipeMediaType.Image),[".mp4"]=("video/mp4",RecipeMediaType.Video),[".webm"]=("video/webm",RecipeMediaType.Video) };
 private readonly string _directory; private readonly RecipeMediaOptions _options; private readonly ILogger<LocalRecipeMediaStorage> _logger;
 public LocalRecipeMediaStorage(IWebHostEnvironment environment,IOptions<RecipeMediaOptions> options,ILogger<LocalRecipeMediaStorage> logger) { _directory=Path.Combine(environment.WebRootPath ?? Path.Combine(environment.ContentRootPath,"wwwroot"),"images","recipes"); _options=options.Value; _logger=logger; }
 public async Task<string> SaveAsync(RecipeMediaUpload upload,CancellationToken ct=default) { if(upload.Length<=0) throw new RecipeMediaValidationException("invalid_media","A media file is required."); var ext=Path.GetExtension(upload.FileName); if(!Extensions.TryGetValue(ext,out var expected)||!string.Equals(expected.ContentType,upload.ContentType,StringComparison.OrdinalIgnoreCase)) throw new RecipeMediaValidationException("unsupported_media_type","Only JPEG, PNG, WEBP, MP4, and WebM media are supported."); var allowed=expected.Type==RecipeMediaType.Image?_options.AllowedImageContentTypes:_options.AllowedVideoContentTypes; if(!allowed.Contains(upload.ContentType,StringComparer.OrdinalIgnoreCase)) throw new RecipeMediaValidationException("unsupported_media_type","The declared media type is not allowed."); var limit=expected.Type==RecipeMediaType.Image?_options.MaxImageFileSizeBytes:_options.MaxVideoFileSizeBytes; if(upload.Length>limit) throw new RecipeMediaValidationException("media_too_large","Media exceeds the allowed size."); if(!await HasExpectedSignatureAsync(upload.Content,expected.ContentType,ct)) throw new RecipeMediaValidationException("invalid_media","The uploaded file signature does not match its type."); Directory.CreateDirectory(_directory); var name=Guid.NewGuid().ToString("N")+ext.ToLowerInvariant(); await using var output=new FileStream(Path.Combine(_directory,name),FileMode.CreateNew,FileAccess.Write,FileShare.None,81920,true); await upload.Content.CopyToAsync(output,ct); return PublicPrefix+name; }
 public Task DeleteAsync(string url,CancellationToken ct=default) { if(!TryGetManagedPath(url,out var path)) return Task.CompletedTask; try { if(File.Exists(path)) File.Delete(path); } catch(Exception ex) { _logger.LogWarning(ex,"Could not remove managed recipe media {Url}",url); } return Task.CompletedTask; }
 private bool TryGetManagedPath(string url,out string path) { path=string.Empty; if(!url.StartsWith(PublicPrefix,StringComparison.Ordinal)||url.Contains("..",StringComparison.Ordinal)||url.Contains('\\')) return false; var name=url[PublicPrefix.Length..]; if(string.IsNullOrWhiteSpace(name)||name!=Path.GetFileName(name)) return false; var candidate=Path.GetFullPath(Path.Combine(_directory,name)); var root=Path.GetFullPath(_directory)+Path.DirectorySeparatorChar; if(!candidate.StartsWith(root,StringComparison.Ordinal)) return false; path=candidate; return true; }
 private static async Task<bool> HasExpectedSignatureAsync(Stream stream,string type,CancellationToken ct) { if(!stream.CanSeek)return false; var pos=stream.Position;var header=new byte[256];var read=await stream.ReadAsync(header.AsMemory(),ct);stream.Position=pos; return type switch { "image/jpeg"=>read>=3&&header[0]==0xFF&&header[1]==0xD8&&header[2]==0xFF,"image/png"=>read>=8&&header.AsSpan(0,8).SequenceEqual(new byte[]{137,80,78,71,13,10,26,10}),"image/webp"=>read>=12&&header.AsSpan(0,4).SequenceEqual("RIFF"u8)&&header.AsSpan(8,4).SequenceEqual("WEBP"u8),"video/mp4"=>HasMp4Ftyp(header.AsSpan(0,read)),"video/webm"=>read>=8&&header.AsSpan(0,4).SequenceEqual(new byte[]{0x1A,0x45,0xDF,0xA3})&&System.Text.Encoding.ASCII.GetString(header,0,read).Contains("webm",StringComparison.OrdinalIgnoreCase),_=>false}; }
 private static bool HasMp4Ftyp(ReadOnlySpan<byte> bytes) { for(var offset=0;offset+8<=bytes.Length&&offset<64;) { var size=System.Buffers.Binary.BinaryPrimitives.ReadUInt32BigEndian(bytes[offset..]); if(bytes.Slice(offset+4,4).SequenceEqual("ftyp"u8)) return size>=8; if(size<8||size>bytes.Length-offset)return false;offset+=(int)size;}return false; }
}
