import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { HttpClient, HttpParams } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { ToastrService } from 'ngx-toastr';
import { AdminNavComponent } from '../admin-nav.component';
import { API_BASE_URL } from '../../../app-api.config';
@Component({standalone:true,imports:[CommonModule,FormsModule,RouterLink,AdminNavComponent],template:`<section class="page-shell"><app-admin-nav/><header><p class="ui-label">Admin</p><h1 class="page-title">{{ title }}</h1></header><input class="form-control" [(ngModel)]="search" (keyup.enter)="load(1)" placeholder="Search"><p *ngIf="loading">Loading…</p><div class="alert alert-danger" *ngIf="error">{{error}}</div><article *ngFor="let item of items" class="admin-item"><div><strong>{{item.title || item.content || item.comment}}</strong><p>{{item.author}} · {{item.recipeTitle || item.category || ''}} {{item.rating ? '· '+item.rating+'/5' : ''}}</p><small>{{item.createdAt | date}}</small></div><div><a *ngIf="kind==='recipes'" class="btn btn-secondary-app" [routerLink]="['/recipes',item.id]">View</a> <button class="btn btn-danger-app" [disabled]="acting===item.id" (click)="remove(item)">{{acting===item.id?'Deleting…':'Delete'}}</button></div></article><nav *ngIf="totalPages>1"><button class="btn btn-secondary-app" [disabled]="page===1" (click)="load(page-1)">Previous</button> Page {{page}} of {{totalPages}} <button class="btn btn-secondary-app" [disabled]="page===totalPages" (click)="load(page+1)">Next</button></nav></section>`,styles:[`.admin-item{display:flex;justify-content:space-between;gap:1rem;margin:1rem 0;padding:1rem;border:1px solid var(--color-border);border-radius:var(--radius-lg)}@media(max-width:600px){.admin-item{align-items:start;flex-direction:column}}`]})
export class ModerationComponent implements OnInit { kind='recipes';title='Recipes';items:any[]=[];search='';page=1;totalPages=0;loading=false;acting='';error=''; constructor(private route:ActivatedRoute,private http:HttpClient,private toast:ToastrService){} ngOnInit(){this.kind=this.route.snapshot.data['kind'];this.title=this.kind[0].toUpperCase()+this.kind.slice(1);this.load();} load(page=1){this.page=page;this.loading=true;let params=new HttpParams().set('page',page).set('pageSize',20).set('search',this.search);this.http.get<any>(`${API_BASE_URL}/admin/${this.kind}`,{params}).subscribe({next:r=>{this.items=r.items;this.totalPages=r.totalPages;this.loading=false},error:e=>{this.error=e.error?.message||'Unable to load records.';this.loading=false}})} remove(item:any){if(!confirm(`Delete this ${this.kind.slice(0,-1)}?`))return;this.acting=item.id;const url=this.kind==='recipes'?`${API_BASE_URL}/recipes/${item.id}`:this.kind==='comments'?`${API_BASE_URL}/comments/${item.id}`:`${API_BASE_URL}/reviews/${item.id}`;this.http.delete(url).subscribe({next:()=>{this.toast.success(`${this.kind.slice(0,-1)} removed.`);this.acting='';this.load(this.page)},error:e=>{this.toast.error(e.error?.message||'Action failed.');this.acting=''}})}}
